name: Deploy to Hosting

on:
  push:
    branches:
      - main  # Или другая ветка, с которой нужно деплоить

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build blocks
        run: |
          cd plugins/blocks-gamestore
          npm install
          npm run build

      - name: Deploy plugins via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "plugins/*"
          #target: "/path/to/your/wp-content/plugins/"

      - name: Deploy themes via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "themes/*"
          #target: "/path/to/your/wp-content/themes/"
        
      - name: Deploy mu-plugins via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "mu-plugins/*"
          #target: "/path/to/your/wp-content/mu-plugins/"